namespace LeapReleaser
{
    public class CMakeHelper
    {
        public static string Base { get; private set; } = "# Root cmake\r\ncmake_minimum_required(VERSION 3.22)\r\n\r\nProject(Example VERSION 1.0.0)\r\nset(CMAKE_CXX_STANDARD 20)\r\nset(CMAKE_CXX_STANDARD_REQUIRED ON)\r\n\r\nif (MSVC)\r\n    add_compile_options(/W4 /WX)\r\nelse()\r\n    add_compile_options(-Wall -Wextra -Werror)\r\nendif()\r\n\r\n# Copy files\r\nset(DATA_FILES \"${CMAKE_CURRENT_SOURCE_DIR}/Data\")\r\nset(DESTINATION_COPY \"${CMAKE_BINARY_DIR}/Example/Data\")\r\n\r\n# Engine\r\nadd_subdirectory(3rdParty)\r\n\r\n# Game Project\r\nadd_subdirectory(Example)";
        public static string ThirdParty { get; private set; } = "# 3rdParty CMake\r\nadd_subdirectory(3rdParty)\r\nadd_subdirectory(Engine)";
        public static string Engine { get; private set; } = "# Engine CMake\r\nadd_subdirectory(AudioEngine)\r\nadd_subdirectory(EngineUtils)\r\nadd_subdirectory(GraphicsEngine)\r\nadd_subdirectory(InputEngine)\r\nadd_subdirectory(LeapEngine)\r\nadd_subdirectory(NetworkingEngine)\r\nadd_subdirectory(PhysicsEngine)";

        public static string Settings { get; private set; } = "{\r\n  \"configurations\": [\r\n    {\r\n      \"name\": \"x64-Debug\",\r\n      \"generator\": \"Ninja\",\r\n      \"configurationType\": \"Debug\",\r\n      \"inheritEnvironments\": [ \"msvc_x64_x64\" ],\r\n      \"buildRoot\": \"${projectDir}\\\\out\\\\build\\\\${name}\",\r\n      \"installRoot\": \"${projectDir}\\\\out\\\\install\\\\${name}\",\r\n      \"cmakeCommandArgs\": \"-DIsConsole=FALSE\",\r\n      \"buildCommandArgs\": \"\",\r\n      \"ctestCommandArgs\": \"\"\r\n    },\r\n    {\r\n      \"name\": \"x64-Release\",\r\n      \"generator\": \"Ninja\",\r\n      \"configurationType\": \"RelWithDebInfo\",\r\n      \"buildRoot\": \"${projectDir}\\\\out\\\\build\\\\${name}\",\r\n      \"installRoot\": \"${projectDir}\\\\out\\\\install\\\\${name}\",\r\n      \"cmakeCommandArgs\": \"-DIsConsole=FALSE\",\r\n      \"buildCommandArgs\": \"\",\r\n      \"ctestCommandArgs\": \"\",\r\n      \"inheritEnvironments\": [ \"msvc_x64_x64\" ]\r\n    },\r\n    {\r\n      \"name\": \"x64-Debug-Console\",\r\n      \"generator\": \"Ninja\",\r\n      \"configurationType\": \"Debug\",\r\n      \"buildRoot\": \"${projectDir}\\\\out\\\\build\\\\${name}\",\r\n      \"installRoot\": \"${projectDir}\\\\out\\\\install\\\\${name}\",\r\n      \"cmakeCommandArgs\": \"-DIsConsole=TRUE\",\r\n      \"buildCommandArgs\": \"\",\r\n      \"ctestCommandArgs\": \"\",\r\n      \"inheritEnvironments\": [ \"msvc_x64_x64\" ]\r\n    },\r\n    {\r\n      \"name\": \"x64-Release-Console\",\r\n      \"generator\": \"Ninja\",\r\n      \"configurationType\": \"RelWithDebInfo\",\r\n      \"buildRoot\": \"${projectDir}\\\\out\\\\build\\\\${name}\",\r\n      \"installRoot\": \"${projectDir}\\\\out\\\\install\\\\${name}\",\r\n      \"cmakeCommandArgs\": \"-DIsConsole=TRUE\",\r\n      \"buildCommandArgs\": \"\",\r\n      \"ctestCommandArgs\": \"\",\r\n      \"inheritEnvironments\": [ \"msvc_x64_x64\" ],\r\n      \"variables\": []\r\n    }\r\n  ]\r\n}\r\n";


        public static string GenerateEngine(string includeVar, string libVar, string libName)
        {
            return $"# Subengine CMake\r\nset({includeVar} \"${{CMAKE_CURRENT_SOURCE_DIR}}/include\" CACHE PATH \"\")\r\n\r\nif(CMAKE_BUILD_TYPE STREQUAL \"Debug\")\r\n\tset({libVar} \"${{CMAKE_CURRENT_SOURCE_DIR}}/lib/debug/{libName}.lib\" CACHE PATH \"\")\r\nelse()\r\n\tset({libVar} \"${{CMAKE_CURRENT_SOURCE_DIR}}/lib/release/{libName}.lib\" CACHE PATH \"\")\r\nendif()";
        }
    }
}
